"""
discount_stats.py - Quantify the Korea Discount with Newey-West HAC inference.

Computes KOSPI P/B spread against two benchmarks:
  - TOPIX    (developed peer; core thesis benchmark per D-04)
  - MSCI_EM  (EM peer; context benchmark per D-04)

SP500 is excluded from discount computation (context line in Figure 1 only,
per D-04).

Statistical method (D-06):
  Paired t-test via sm.OLS(spread, constant).get_robustcov_results(
      cov_type="HAC", maxlags=12
  )
  Newey-West HAC standard errors correct for autocorrelation in monthly
  valuation data.
  maxlags=12 is the paper convention for monthly data (one year of lags).

Units (D-05): P/B points (e.g., -0.177x) - NOT basis points.

Outputs:
  output/tables/discount_stats.csv - machine-readable for Phase 3 consumption
  output/tables/discount_stats.tex - LaTeX \\newcommand fragment for abstract
"""
import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import statsmodels.api as sm

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import config

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s: %(message)s",
    stream=sys.stdout,
)


def compute_hac_spread(
    kospi: pd.Series,
    benchmark: pd.Series,
    benchmark_name: str,
    maxlags: int = 12,
) -> dict:
    """Compute mean spread with Newey-West HAC standard errors."""
    spread = (kospi - benchmark).dropna().values
    model = sm.OLS(spread, np.ones(len(spread))).fit()
    hac = model.get_robustcov_results(cov_type="HAC", maxlags=maxlags)

    return {
        "benchmark": benchmark_name,
        "n": int(len(spread)),
        "mean": float(hac.params[0]),
        "nw_se": float(hac.bse[0]),
        "t_stat": float(hac.tvalues[0]),
        "ci_lower": float(hac.conf_int()[0, 0]),
        "ci_upper": float(hac.conf_int()[0, 1]),
    }


def main() -> None:
    """Compute headline Korea Discount statistics and write table artifacts."""
    df = pd.read_parquet(config.PROCESSED_DIR / "panel.parquet")
    df_2024 = df[df["date"] <= pd.Timestamp("2024-12-31")].copy()

    def pb_series(country: str) -> pd.Series:
        return (
            df_2024[df_2024["country"] == country]
            .set_index("date")["pb"]
            .sort_index()
        )

    kospi = pb_series("KOSPI")
    topix = pb_series("TOPIX")
    msci = pb_series("MSCI_EM")

    results = [
        compute_hac_spread(kospi, topix, "TOPIX", maxlags=12),
        compute_hac_spread(kospi, msci, "MSCI_EM", maxlags=12),
    ]

    for row in results:
        logging.info(
            "KOSPI - %s: mean=%.4fx, NW SE=%.4f, t=%.2f, 95%% CI [%.3f, %.3f]",
            row["benchmark"],
            row["mean"],
            row["nw_se"],
            row["t_stat"],
            row["ci_lower"],
            row["ci_upper"],
        )

    tables_dir = config.OUTPUT_DIR / "tables"
    tables_dir.mkdir(parents=True, exist_ok=True)

    csv_path = tables_dir / "discount_stats.csv"
    pd.DataFrame(results).to_csv(csv_path, index=False)
    logging.info("Saved %s", csv_path)

    tex_lines = [
        "% Korea Discount magnitude - auto-generated by discount_stats.py\n",
        "% Usage in LaTeX: \\korDiscountTOPIX, \\korDiscountMSCIEM, etc.\n",
        "%\n",
    ]
    for row in results:
        safe_name = row["benchmark"].replace("_", "")
        tex_lines.extend(
            [
                f"\\newcommand{{\\korDiscount{safe_name}}}{{{row['mean']:.3f}x}}\n",
                f"\\newcommand{{\\korDiscount{safe_name}TStat}}{{{row['t_stat']:.2f}}}\n",
                (
                    f"\\newcommand{{\\korDiscount{safe_name}CILower}}"
                    f"{{{row['ci_lower']:.3f}x}}\n"
                ),
                (
                    f"\\newcommand{{\\korDiscount{safe_name}CIUpper}}"
                    f"{{{row['ci_upper']:.3f}x}}\n"
                ),
                "%\n",
            ]
        )

    tex_path = tables_dir / "discount_stats.tex"
    tex_path.write_text("".join(tex_lines), encoding="utf-8")
    logging.info("Saved %s", tex_path)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
