"""
geo_risk.py - Estimate KOSPI valuation association with Korea GPR escalation.

Outputs:
  output/tables/geo_risk_results.csv - regression coefficients and GPR threshold
  output/tables/table3_geo_risk.tex - publication-ready result with caveat
"""
import logging
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels.formula.api as smf

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import config

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s: %(message)s",
    stream=sys.stdout,
)

GPR_ESCALATION_QUANTILE = 0.75
STUDY_START = pd.Timestamp("2004-01-01")
STUDY_END = pd.Timestamp("2024-12-31")
GPR_FILENAME = "data_gpr_export.xls"
GPR_COLUMN = "GPRC_KOR"

TABLE_NOTE = (
    "Partial identification caveat: the GPR-Korea escalation coefficient is an "
    "association, not a pure causal effect, because GPRC_KOR may also capture "
    "global risk-off episodes."
)


def load_gpr_korea() -> tuple[pd.DataFrame, float]:
    """Load Korea country-level GPR and construct the escalation dummy."""
    gpr_path = config.RAW_DIR / GPR_FILENAME
    gpr = pd.read_excel(
        gpr_path,
        usecols=["month", GPR_COLUMN],
        engine="xlrd",
    )
    gpr = gpr.rename(columns={"month": "date"})
    gpr["date"] = pd.to_datetime(gpr["date"])
    gpr = gpr.dropna(subset=[GPR_COLUMN])

    study = gpr[
        (gpr["date"] >= STUDY_START) & (gpr["date"] <= STUDY_END)
    ].copy()
    GPR_KOREA_ESCALATION_THRESHOLD = study[GPR_COLUMN].quantile(
        GPR_ESCALATION_QUANTILE
    )
    study["gpr_escalation_dummy"] = (
        study[GPR_COLUMN] > GPR_KOREA_ESCALATION_THRESHOLD
    ).astype(int)

    return study, float(GPR_KOREA_ESCALATION_THRESHOLD)


def build_geo_regression_data(panel: pd.DataFrame, gpr: pd.DataFrame) -> pd.DataFrame:
    """Merge monthly KOSPI/TOPIX P/B values with Korea GPR escalation data."""
    panel_study = panel[panel["date"] <= STUDY_END].copy()
    pb = (
        panel_study.pivot(index="date", columns="country", values="pb")
        .reset_index()
        .rename(columns={"KOSPI": "kospi_pb", "TOPIX": "topix_pb"})
    )
    pb["month_period"] = pb["date"].dt.to_period("M")

    gpr_study = gpr.copy()
    gpr_study["date"] = pd.to_datetime(gpr_study["date"])
    gpr_study["month_period"] = gpr_study["date"].dt.to_period("M")

    merged = pb.merge(
        gpr_study[[GPR_COLUMN, "gpr_escalation_dummy", "month_period"]],
        on="month_period",
        how="inner",
    )
    merged["year"] = merged["date"].dt.year.astype("category")
    merged = merged.sort_values("date")

    required = ["kospi_pb", "topix_pb", "gpr_escalation_dummy"]
    return merged.dropna(subset=required).reset_index(drop=True)


def estimate_geo_model(reg_df: pd.DataFrame):
    """Estimate KOSPI P/B on GPR escalation, TOPIX P/B, and year FE."""
    model = smf.ols(
        "kospi_pb ~ gpr_escalation_dummy + topix_pb + C(year)",
        data=reg_df,
    ).fit()
    hc3 = model.get_robustcov_results(cov_type="HC3")
    return hc3


def _robust_term_row(result, term: str, note: str = "") -> dict:
    """Extract a named coefficient row from a statsmodels robust result."""
    names = result.model.exog_names
    idx = names.index(term)
    return {
        "term": term,
        "estimate": float(result.params[idx]),
        "std_error": float(result.bse[idx]),
        "t_stat": float(result.tvalues[idx]),
        "p_value": float(result.pvalues[idx]),
        "note": note,
    }


def write_results(
    result,
    threshold: float,
    reg_df: pd.DataFrame,
    tables_dir: Path,
) -> None:
    """Write machine-readable and LaTeX geopolitical risk results."""
    tables_dir.mkdir(parents=True, exist_ok=True)

    rows = [
        _robust_term_row(result, "gpr_escalation_dummy", TABLE_NOTE),
        _robust_term_row(result, "topix_pb", "TOPIX P/B control."),
        {
            "term": "GPR_KOREA_ESCALATION_THRESHOLD",
            "estimate": threshold,
            "std_error": pd.NA,
            "t_stat": pd.NA,
            "p_value": pd.NA,
            "note": (
                f"75th percentile of {GPR_COLUMN} over "
                f"{STUDY_START:%Y-%m} to {STUDY_END:%Y-%m}."
            ),
        },
    ]

    results_path = tables_dir / "geo_risk_results.csv"
    pd.DataFrame(rows).to_csv(results_path, index=False)
    logging.info("Saved %s", results_path)

    gpr_row = rows[0]
    topix_row = rows[1]
    tex_lines = [
        "% Geo-risk regression table - auto-generated by geo_risk.py\n",
        "\\begin{table}[htbp]\n",
        "\\centering\n",
        "\\caption{Korea Geopolitical Risk and KOSPI Valuation}\n",
        "\\begin{tabular}{lrrrr}\n",
        "\\toprule\n",
        "Term & Estimate & Std. Error & t-stat & p-value \\\\\n",
        "\\midrule\n",
        (
            f"GPR escalation dummy & {gpr_row['estimate']:.2f} & "
            f"{gpr_row['std_error']:.2f} & {gpr_row['t_stat']:.2f} & "
            f"{gpr_row['p_value']:.2f} \\\\\n"
        ),
        (
            f"TOPIX P/B & {topix_row['estimate']:.2f} & "
            f"{topix_row['std_error']:.2f} & {topix_row['t_stat']:.2f} & "
            f"{topix_row['p_value']:.2f} \\\\\n"
        ),
        "\\bottomrule\n",
        "\\end{tabular}\n",
        (
            f"\\begin{{flushleft}}\\footnotesize N = {len(reg_df)} monthly "
            "observations. Year fixed effects included. "
            f"GPR escalation threshold = {threshold:.2f}. {TABLE_NOTE}"
            "\\end{flushleft}\n"
        ),
        "\\end{table}\n",
    ]
    table_path = tables_dir / "table3_geo_risk.tex"
    table_path.write_text("".join(tex_lines), encoding="utf-8")
    logging.info("Saved %s", table_path)


def plot_geo_risk(reg_df: pd.DataFrame) -> None:
    """Plot Korea GPR escalation months against KOSPI and TOPIX valuations."""
    sns.set_theme(style="whitegrid")
    fig, ax_gpr = plt.subplots(figsize=(10, 5))
    ax_val = ax_gpr.twinx()

    for _, row in reg_df[reg_df["gpr_escalation_dummy"] == 1].iterrows():
        month_start = row["month_period"].to_timestamp(how="start")
        month_end = row["month_period"].to_timestamp(how="end")
        ax_gpr.axvspan(month_start, month_end, color="lightgrey", alpha=0.35, lw=0)

    ax_gpr.plot(
        reg_df["date"],
        reg_df[GPR_COLUMN],
        color="#4c78a8",
        linewidth=1.2,
        label="GPRC_KOR",
    )
    ax_val.plot(
        reg_df["date"],
        reg_df["kospi_pb"],
        color="#f58518",
        linewidth=1.4,
        label="KOSPI P/B",
    )
    ax_val.plot(
        reg_df["date"],
        reg_df["topix_pb"],
        color="#54a24b",
        linewidth=1.4,
        label="TOPIX P/B",
    )

    ax_gpr.set_xlabel("Date")
    ax_gpr.set_ylabel("Korea GPR Index")
    ax_val.set_ylabel("Price-to-Book Ratio (P/B)")
    ax_gpr.set_title(
        "Figure 3: Korea Geopolitical Risk and Valuation, 2004-2024",
        fontsize=11,
    )
    ax_gpr.xaxis.set_major_locator(mdates.YearLocator(4))
    ax_gpr.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))

    handles_gpr, labels_gpr = ax_gpr.get_legend_handles_labels()
    handles_val, labels_val = ax_val.get_legend_handles_labels()
    ax_gpr.legend(
        handles_gpr + handles_val,
        labels_gpr + labels_val,
        loc="upper left",
        frameon=True,
    )

    output_path = config.OUTPUT_DIR / "figures" / "figure3_geo_risk.pdf"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
        format="pdf",
        metadata={"CreationDate": None, "ModDate": None},
    )
    plt.close(fig)
    logging.info("Saved Figure 3 to %s", output_path)


def main() -> None:
    """Run the geopolitical risk sub-analysis and write output artifacts."""
    panel = pd.read_parquet(config.PROCESSED_DIR / "panel.parquet")
    gpr, threshold = load_gpr_korea()
    reg_df = build_geo_regression_data(panel, gpr)
    result = estimate_geo_model(reg_df)

    logging.info(
        "GPR escalation threshold %.4f; escalation share %.3f; N=%d",
        threshold,
        reg_df["gpr_escalation_dummy"].mean(),
        len(reg_df),
    )
    write_results(result, threshold, reg_df, config.OUTPUT_DIR / "tables")
    plot_geo_risk(reg_df)


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
